### ISSUE TITLE
Setting the calender's scope/view according to admin demands.

### ISSUE THREAD

**Issue by liorsap1** [flashxyz/BookMe#13]
Setting the calender's scope/view according to admin demands.

**Comment by nirbm** [comment]
lior, when the time comes I want you to get the calendar settings from the database and assign them to the current calendar design when generating it.

**Comment by liorsap1** [comment]
o.k. this part is required cooperation from the sever team.

**Comment by rotemsd** [comment]
tell me what do you need to pull from DB.

**Comment by nirbm** [comment]
thank you all the, see the matter as closed
