### ISSUE TITLE
offer available rooms to the client, according to his specific demands

### ISSUE THREAD

**Issue by liorsap1** [flashxyz/BookMe#31]
Add client's reservation page.

**Comment by nirbm** [comment]
Lior, you need to work on this issue ASAP.
you need to pull the available rooms according to the requested capabilities and availability, using a sql query. please get it to work with rotem ! @liorsap1 @rotemsd

**Comment by rotemsd** [comment]
almost done, need to filter rooms by activate days

**Comment by nirbm** [comment]
rotem where are we standing? @rotemsd

**Comment by rotemsd** [comment]
i am working on it, i hope to finish it very soon

**Comment by rotemsd** [comment]
Done!!!!!!!!

579320f6444558c6d5f85e5379877fdadef5bbff
