### ISSUE TITLE
Review the SRS 

### ISSUE THREAD

**Issue by rotemsd** [flashxyz/BookMe#42]

**Comment by ItamarShDev** [comment]
well, i didnt review it, cause i see the old SRS file in the wiki.
did i miss something?

**Comment by rotemsd** [comment]
yes..
here is the link:
https://github.com/flashxyz/BookMe/blob/master/docs/SRSfinal.docx?raw=true

**Comment by ItamarShDev** [comment]
please create a page linking to this :+1:
