### ISSUE TITLE
Review the ZFR

### ISSUE THREAD

**Issue by liorsap1** [flashxyz/BookMe#5]
First edit the zero features release

**Comment by rotemsd** [comment]
We start the new project 3 weeks after everyone, so because that delay we have only 3 iteration.

**Comment by robi-y** [comment]
Fine, I still don't see it reflected in the [milestones](https://github.com/flashxyz/BookMe/milestones). Please update @ItamarShDev when you are ready for ZFR review.
I'm updating your project name to BookMe in grade sheet and also tell it to ignore iteration 4

**Comment by rotemsd** [comment]
we just update the dates at milestones and assign itamar for check the docs

**Comment by ItamarShDev** [comment]
I dont see any Prototype link in the ZFR, nor documentation of any work.
also your MVP planning is lacking to many aspects

**Comment by robi-y** [comment]
Graded the missing parts, good luck
