### ISSUE TITLE
withdraw time and date information from calendar to roomSelector div

### ISSUE THREAD

**Issue by nirbm** [flashxyz/BookMe#50]
for integrated flow between calendar and "roomSelector" div

**Comment by Hudeda** [comment]
I've managed to withdraw the current date from the calendar view and integrate it with the value of the date request from the roomSelector. now working on syncronizing the start/end hours....

**Comment by nirbm** [comment]
great! thanks Adam I'm counting on you !!!!

**Comment by Hudeda** [comment]
solved!
