### ISSUE TITLE
Add some more Room options to SQL and admin page

### ISSUE THREAD

**Issue by flashxyz** [flashxyz/BookMe#58]
each room should have it's own restrictions in addition to the general rooms group options.
From time, To time, active days. 
we should create forms in room options and matching SQL table as well.

**Comment by nirbm** [comment]
sounds great! would you mind adding 'Group general capabilities' TLV/strings array to the group_options as well? I could really use it for the form generation, in order to create checkboxes for the user to chose from...

**Comment by flashxyz** [comment]
Rotem is responsible for this part, i will assign him for this task.
nevertheless i have added some more room options as needed.
