### ISSUE TITLE
BUILD and DESIGN the eventClick form

### ISSUE THREAD

**Issue by nirbm** [flashxyz/BookMe#69]
This form (Dialog) - will display room reservation data when **CLICKING AN EVENT** on the calendar.
It should consist at least: 
- Reservation details : begin&end time of a room's reservation, room description and capabilities.
- close button : for closing the dialog
- delete button, or a cancel reservation button : for allowing the user to clear the reservation 
The design should be bootstraped and animated, if possible. 
goodluck Lior.

**Comment by liorsap1** [comment]
Done, bootstrap window is now open when you click on existing event with buttons and edit room options.

**Comment by nirbm** [comment]
Exciting work Lior! please notice, the first task task is about withdrawing the room's reservation data from the DB. please close the issue after that is done. that is a big issue! reopening, thanks.

**Comment by liorsap1** [comment]
very well sir! i am on my mission to target the database!

**Comment by nirbm** [comment]
Your next mission is pulling the room's description and services ! :100: 

@liorsap1

**Comment by liorsap1** [comment]
right now we have the turn on capabilities and nice popup for the event click
