### ISSUE TITLE
Create a Test user account for room reservations testing

### ISSUE THREAD

**Issue by nirbm** [flashxyz/BookMe#70]
In the previous iteration, we successfully pulled data concerning the RoomGroups and Calendar looks&behavior . There are still many open improvements to be done, but the main features stands.
**Coming next**: As you all know, in the following iteration we will work mainly on the connection and interaction with the DB **PER USER** . Meaning - pulling relevant data, such as: 

- reservations made by the user.
- configure users restrictions.
- enable rooms offering according to user's demands, etc. 

for that, we are going to need to create at least 2 'dummy' users for testing.
Until we get real users access from Yair (what will probably won't happen at the semester time),
we have to perform all the testing on these fake users.
everyone on the team should be aware of this task. goodluck

**Comment by flashxyz** [comment]
done!
now each one of us have It's own user to test
