### ISSUE TITLE
add img url field for the rooms db table, as well for the rooms group theme img

### ISSUE THREAD

**Issue by nirbm** [flashxyz/BookMe#71]
FYI , we need to cover this capability.

**Comment by nirbm** [comment]
rotem, you can also do it when you have time :) 
@rotemsd

**Comment by rotemsd** [comment]
ok i will do it

**Comment by nirbm** [comment]
thank you !

**Comment by rotemsd** [comment]
It was an optional feature and we don't have enough time to do it... We are working hard to fix important bugs..
