### ISSUE TITLE
Custom Notification Popup Div

### ISSUE THREAD

**Issue by nirbm** [flashxyz/BookMe#77]
I just noticed that the user is not being notified of wrong/missing input when clicking a button.
Lior, please design something nice, alert-like popup, to notify the user of wrong or missing input. If possible in this time frame, mark the fields with the wrong input. 
This is a big and important task and I'm counting on you, thanks !

**Comment by liorsap1** [comment]
Yes! I will try to add a nice alert to valid the inputs of the user.

**Comment by liorsap1** [comment]
Using very nice alerts calling sweet alert which communicate with the user and alert on bad inputs.
