### ISSUE TITLE
BUG: Selection of multiple time windows in the calendar

### ISSUE THREAD

**Issue by flashxyz** [flashxyz/BookMe#85]
when i select multiple time windows in the calendar it wont check correctly for an available room.
basically it checks only start time and end time but not anything between.
wee need to fix it @rotemsd. maybe we will need some help from calendar team. @Hudeda

**Comment by nirbm** [comment]
I beleive rotem is working on it... by tommorow we will fix it I assure you.
nice bug

**Comment by nirbm** [comment]
@flashxyz 
FYI, we separated the begin and end hours to an array of single slots for easier comparison against the database tables... soon it will be ready...

**Comment by rotemsd** [comment]
FIXED 

f4a8753ebfee8f50b41ede784f7e96f128fb60f3

4d9f8e441ad600319bd92ec9ff110dc26487fd58
