### ISSUE TITLE
BUG: time length selection limit

### ISSUE THREAD

**Issue by flashxyz** [flashxyz/BookMe#86]
if the current calendar's max limit is 3 hours (3 windows of selection for example) and i chose more then that in the same day i will get an error message :  "אינך יכול להזמין יותר מ - 3 משבצות זמן!"
but if my time selection is crossing the current day and continues to another day i will get the error message of : "!תאריך ושעה כבר עברו, בחר תאריך ושעה עדכניים" and it's obviously should be "אינך יכול להזמין יותר מ - 3 משבצות זמן!".

**Comment by nirbm** [comment]
nice elya I also saw that bug but it was too late in the night to report LOL

**Comment by nirbm** [comment]
@liorsap1

**Comment by flashxyz** [comment]
[Bug Fixed - Click to see commit](https://github.com/flashxyz/BookMe/commit/bd5e849194fe8decf9be267f6cd399b2826299e0)
